package dh

import (
	"bytes"
	"encoding/hex"
	"testing"

	clatter "github.com/shurlinet/go-clatter"
)

func TestX25519_GenerateKeypair(t *testing.T) {
	x := NewX25519()
	rng := clatter.NewDummyRng(0xdeadbeef)

	kp, err := x.GenerateKeypair(rng)
	if err != nil {
		t.Fatal(err)
	}
	if len(kp.Public) != 32 {
		t.Fatalf("expected 32-byte public key, got %d", len(kp.Public))
	}
	if len(kp.SecretSlice()) != 32 {
		t.Fatalf("expected 32-byte secret key, got %d", len(kp.SecretSlice()))
	}
}

func TestX25519_Deterministic(t *testing.T) {
	x := NewX25519()
	rng1 := clatter.NewDummyRng(42)
	rng2 := clatter.NewDummyRng(42)

	kp1, _ := x.GenerateKeypair(rng1)
	kp2, _ := x.GenerateKeypair(rng2)

	if !bytes.Equal(kp1.Public, kp2.Public) {
		t.Fatal("same seed should produce same public key")
	}
}

func TestX25519_DH(t *testing.T) {
	x := NewX25519()
	rng := clatter.NewDummyRng(0)

	alice, _ := x.GenerateKeypair(rng)
	bob, _ := x.GenerateKeypair(rng)

	ss1, err := x.DH(alice, bob.Public)
	if err != nil {
		t.Fatal(err)
	}
	ss2, err := x.DH(bob, alice.Public)
	if err != nil {
		t.Fatal(err)
	}

	if !bytes.Equal(ss1, ss2) {
		t.Fatal("DH shared secrets should match")
	}
	if len(ss1) != 32 {
		t.Fatalf("expected 32-byte shared secret, got %d", len(ss1))
	}
}

// TestX25519_RustInterop verifies that Go's X25519 keygen from DummyRng(0xdeadbeef)
// produces the same public key as Rust Clatter v2.2.0. This is the critical interop
// wire test — if this fails, all vector tests will also fail.
// Expected value generated by: cargo run --bin print_x25519 -p clatter-tests
func TestX25519_RustInterop(t *testing.T) {
	x := NewX25519()
	rng := clatter.NewDummyRng(0xdeadbeef)

	kp, err := x.GenerateKeypair(rng)
	if err != nil {
		t.Fatal(err)
	}

	expectedHex := "f39367a208accc830fb787eb59c4f6a62f3b667484430fdc1281a6dfce895b4f"
	expected, _ := hex.DecodeString(expectedHex)
	if !bytes.Equal(kp.Public, expected) {
		t.Fatalf("X25519 pubkey from DummyRng(0xdeadbeef) does not match Rust Clatter\n  got:    %x\n  expect: %s", kp.Public, expectedHex)
	}
}

func TestX25519_Name(t *testing.T) {
	x := NewX25519()
	if x.Name() != "25519" {
		t.Fatalf("expected '25519', got %q", x.Name())
	}
}

func TestX25519_PubKeyLen(t *testing.T) {
	x := NewX25519()
	if x.PubKeyLen() != 32 {
		t.Fatalf("expected 32, got %d", x.PubKeyLen())
	}
}
